-- Diary(memos) 의미 검색용 임베딩 테이블 + 전체 글 분석 리포트 종류 추가
-- Supabase SQL Editor 에서 1회 실행. 여러 번 실행해도 안전.

-- 1) pgvector 확장
create extension if not exists vector with schema extensions;

-- 2) 임베딩 테이블 (글 하나 = 여러 chunk)
create table if not exists memo_embeddings (
  id              bigint generated by default as identity primary key,
  memo_id         uuid not null references memos(id) on delete cascade,
  user_id         uuid not null default auth.uid() references auth.users(id) on delete cascade,
  chunk_index     int  not null default 0,
  content         text not null,                 -- chunk 원문(제목 포함, HTML 제거)
  embedding       extensions.vector(1536) not null, -- text-embedding-3-small
  memo_updated_at timestamptz not null,          -- 색인 당시 memos.updated_at (재색인 판단용)
  created_at      timestamptz not null default now(),
  unique (memo_id, chunk_index)
);

create index if not exists memo_embeddings_memo_idx on memo_embeddings (memo_id);
create index if not exists memo_embeddings_user_idx on memo_embeddings (user_id);
create index if not exists memo_embeddings_vec_idx
  on memo_embeddings using hnsw (embedding extensions.vector_cosine_ops);

alter table memo_embeddings enable row level security;

drop policy if exists "memo_embeddings_select_own" on memo_embeddings;
create policy "memo_embeddings_select_own" on memo_embeddings
  for select using (auth.uid() = user_id);
drop policy if exists "memo_embeddings_insert_own" on memo_embeddings;
create policy "memo_embeddings_insert_own" on memo_embeddings
  for insert with check (auth.uid() = user_id);
drop policy if exists "memo_embeddings_update_own" on memo_embeddings;
create policy "memo_embeddings_update_own" on memo_embeddings
  for update using (auth.uid() = user_id);
drop policy if exists "memo_embeddings_delete_own" on memo_embeddings;
create policy "memo_embeddings_delete_own" on memo_embeddings
  for delete using (auth.uid() = user_id);

-- 3) 의미 검색 RPC (호출자 권한 → memos/memo_embeddings RLS 그대로 적용)
create or replace function match_memos(
  query_embedding extensions.vector(1536),
  match_count     int  default 8,
  category_name   text default null,
  from_date       date default null,
  to_date         date default null,
  min_similarity  float default 0.15
)
returns table (
  memo_id     uuid,
  title       text,
  category    text,
  created_at  timestamptz,
  chunk_index int,
  content     text,
  similarity  float
)
language sql stable security invoker
as $$
  with scored as (
    select
      e.memo_id,
      m.title,
      c.name as category,
      m.created_at,
      e.chunk_index,
      e.content,
      1 - (e.embedding <=> query_embedding) as similarity
    from memo_embeddings e
    join memos m on m.id = e.memo_id
    left join memo_categories c on c.id = m.category_id
    where (category_name is null or c.name ilike category_name)
      and (from_date is null or (m.created_at at time zone 'Asia/Seoul')::date >= from_date)
      and (to_date   is null or (m.created_at at time zone 'Asia/Seoul')::date <= to_date)
    order by e.embedding <=> query_embedding
    limit greatest(match_count * 3, 12)
  ),
  best as (
    -- 글 하나당 가장 유사한 chunk 1개만
    select distinct on (memo_id) *
    from scored
    order by memo_id, similarity desc
  )
  select memo_id, title, category, created_at, chunk_index, content, similarity
  from best
  where similarity >= min_similarity
  order by similarity desc
  limit match_count;
$$;

-- 4) 색인 필요 글 조회 RPC (미색인 or 수정 후 미갱신)
create or replace function memos_needing_embedding(max_count int default 500)
returns table (id uuid, updated_at timestamptz)
language sql stable security invoker
as $$
  select m.id, coalesce(m.updated_at, m.created_at) as updated_at
  from memos m
  left join (
    select memo_id, max(memo_updated_at) as indexed_at
    from memo_embeddings
    group by memo_id
  ) e on e.memo_id = m.id
  where e.memo_id is null
     or e.indexed_at < coalesce(m.updated_at, m.created_at)
  order by m.created_at desc
  limit max_count;
$$;

-- 5) 색인 현황 RPC
create or replace function memo_embedding_status()
returns table (total_memos bigint, indexed_memos bigint, pending_memos bigint)
language sql stable security invoker
as $$
  with t as (select count(*) as total from memos),
       p as (select count(*) as pending from memos_needing_embedding(100000))
  select t.total, t.total - p.pending, p.pending from t, p;
$$;

-- 6) ai_reports 에 '전체 글 분석(archive)' 종류 허용
alter table ai_reports drop constraint if exists ai_reports_kind_check;
alter table ai_reports add constraint ai_reports_kind_check
  check (kind in ('coach', 'weekly', 'monthly', 'archive'));
